In [4]:
# Import libraries
import sqlite3
import pandas as pd
import os

### Load Outpatient Charges Data

In [5]:
# Define a function that connects to SQLite database, reads each table into a separate DataFrame and adds year column
def load_outpatient_data(db_path):
    # connect to the database
    conn = sqlite3.connect(db_path)

    # Define corresponding years for the tables
    years = [2011, 2012, 2013]

    # Initialize an empty list
    outpatient_dataframes = []

    # Iterate through each year 
    for year in years:
        # Create table_name variable
        table_name = f"outpatient_charges_{year}"
        # Load the table into a dataframe
        df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)

        # Add 'year' column at the beginning
        df.insert(0, 'year', year)

        # Append the list with the dataframes
        outpatient_dataframes.append(df)
    
    # Close connection
    conn.close()
    
    return outpatient_dataframes[0], outpatient_dataframes[1], outpatient_dataframes[2]

In [6]:
# Use 'load_outpatient_data' function to return the dataframes
outpatient_2011, outpatient_2012, outpatient_2013 = load_outpatient_data(r"C:\Users\Injelwa\OneDrive\Desktop\Savannah\outpatient_charges.db")

In [7]:
# Display summary information for the outpatien_2011 data
outpatient_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43372 entries, 0 to 43371
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   year                                 43372 non-null  int64
 1   provider_id                          43372 non-null  int64
 2   provider_name                        43372 non-null  object
 3   provider_street_address              43372 non-null  object
 4   provider_city                        43372 non-null  object
 5   provider_state                       43372 non-null  object
 6   provider_zipcode                     43372 non-null  int64
 7   apc                                  43372 non-null  object
 8   outpatient_services                  43372 non-null  int64
 9   average_estimated_submitted_charges  43372 non-null  float64
 10  average_total_payments               43372 non-null  float64
dtypes: float64(2), int64(4), object(5)
memory usage: 3.6+ MB

In [8]:
# Display summary information for outpatient_2012 data
outpatient_2012.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43783 entries, 0 to 43782
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   year                                 43783 non-null  int64
 1   provider_id                          43783 non-null  int64
 2   provider_name                        43783 non-null  object
 3   provider_street_address              43783 non-null  object
 4   provider_city                        43783 non-null  object
 5   provider_state                       43783 non-null  object
 6   provider_zipcode                     43783 non-null  int64
 7   apc                                  43783 non-null  object
 8   outpatient_services                  43783 non-null  int64
 9   average_estimated_submitted_charges  43783 non-null  float64
 10  average_total_payments               43783 non-null  float64
dtypes: float64(2), int64(4), object(5)
memory usage: 3.7+ MB

In [9]:
# Display summary information for outpatient_2013 data
outpatient_2013.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44355 entries, 0 to 44354
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   year                                 44355 non-null  int64
 1   provider_id                          44355 non-null  int64
 2   provider_name                        44355 non-null  object
 3   provider_street_address              44355 non-null  object
 4   provider_city                        44355 non-null  object
 5   provider_state                       44355 non-null  object
 6   provider_zipcode                     44355 non-null  int64
 7   apc                                  44355 non-null  object
 8   outpatient_services                  44355 non-null  int64
 9   average_estimated_submitted_charges  44355 non-null  float64
 10  average_total_payments               44355 non-null  float64
dtypes: float64(2), int64(4), object(5)
memory usage: 3.7+ MB

In [10]:
# Combine the outpatient charge data for 2011, 2012, and 2013 into a single DataFrame.
outpatient_charges = pd.concat([outpatient_2011, outpatient_2012, outpatient_2013], ignore_index=True)
outpatient_charges.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131510 entries, 0 to 131509
Data columns (total 11 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   year                                 131510 non-null  int64
 1   provider_id                          131510 non-null  int64
 2   provider_name                        131510 non-null  object
 3   provider_street_address              131510 non-null  object
 4   provider_city                        131510 non-null  object
 5   provider_state                       131510 non-null  object
 6   provider_zipcode                     131510 non-null  int64
 7   apc                                  131510 non-null  object
 8   outpatient_services                  131510 non-null  int64
 9   average_estimated_submitted_charges  131510 non-null  float64
 10  average_total_payments               131510 non-null  float64
dtypes: float64(2), int64(4), object(5)
memory usage: 11.0+ MB

In [11]:
outpatient_charges.head()

,year,provider_id,provider_name,provider_street_address,provider_city,provider_state,provider_zipcode,apc,outpatient_services,average_estimated_submitted_charges,average_total_payments
0,2011,30036,CHANDLER REGIONAL MEDICAL CENTER,475 SOUTH DOBSON ROAD,CHANDLER,AZ,85224,0013 - Level II Debridement & Destruction,31,327.515806,49.889032
1,2011,30036,CHANDLER REGIONAL MEDICAL CENTER,475 SOUTH DOBSON ROAD,CHANDLER,AZ,85224,0015 - Level III Debridement & Destruction,936,299.867992,104.416068
2,2011,30036,CHANDLER REGIONAL MEDICAL CENTER,475 SOUTH DOBSON ROAD,CHANDLER,AZ,85224,0020 - Level II Excision/ Biopsy,14,5409.921429,527.096429
3,2011,30036,CHANDLER REGIONAL MEDICAL CENTER,475 SOUTH DOBSON ROAD,CHANDLER,AZ,85224,0078 - Level III Pulmonary Treatment,48,566.275833,101.360000
4,2011,30036,CHANDLER REGIONAL MEDICAL CENTER,475 SOUTH DOBSON ROAD,CHANDLER,AZ,85224,0096 - Level II Noninvasive Physiologic Studies,68,767.822059,107.335294

In [12]:
# Split the 'apc' column in the outpatient_charges DataFrame into two new columns: 'apc_code' and 'apc_service'
outpatient_charges[['apc_code', 'apc_service']] = outpatient_charges['apc'].str.split('-', expand=True)
outpatient_charges.head()

,year,provider_id,provider_name,provider_street_address,provider_city,provider_state,provider_zipcode,apc,outpatient_services,average_estimated_submitted_charges,average_total_payments,apc_code,apc_service
0,2011,30036,CHANDLER REGIONAL MEDICAL CENTER,475 SOUTH DOBSON ROAD,CHANDLER,AZ,85224,0013 - Level II Debridement & Destruction,31,327.515806,49.889032,0013,Level II Debridement & Destruction
1,2011,30036,CHANDLER REGIONAL MEDICAL CENTER,475 SOUTH DOBSON ROAD,CHANDLER,AZ,85224,0015 - Level III Debridement & Destruction,936,299.867992,104.416068,0015,Level III Debridement & Destruction
2,2011,30036,CHANDLER REGIONAL MEDICAL CENTER,475 SOUTH DOBSON ROAD,CHANDLER,AZ,85224,0020 - Level II Excision/ Biopsy,14,5409.921429,527.096429,0020,Level II Excision/ Biopsy
3,2011,30036,CHANDLER REGIONAL MEDICAL CENTER,475 SOUTH DOBSON ROAD,CHANDLER,AZ,85224,0078 - Level III Pulmonary Treatment,48,566.275833,101.360000,0078,Level III Pulmonary Treatment
4,2011,30036,CHANDLER REGIONAL MEDICAL CENTER,475 SOUTH DOBSON ROAD,CHANDLER,AZ,85224,0096 - Level II Noninvasive Physiologic Studies,68,767.822059,107.335294,0096,Level II Noninvasive Physiologic Studies

In [13]:
# Remove the original 'apc' column from the outpatient_charges DataFrame
outpatient_charges.drop(columns='apc', inplace=True)

In [14]:
# Get the unique values in the 'apc_service'
outpatient_charges['apc_service'].unique()

array([' Level II Debridement & Destruction',
       ' Level III Debridement & Destruction',
       ' Level II Excision/ Biopsy', ' Level III Pulmonary Treatment',
       ' Level II Noninvasive Physiologic Studies',
       ' Level I Nerve Injections',
       ' Level I Diagnostic and Screening Ultrasound',
       ' Level III Diagnostic and Screening Ultrasound',
       ' Level II Echocardiogram Without Contrast',
       ' Magnetic Resonance Imaging and Magnetic Resonance Angiography without Contrast',
       ' Level II Pulmonary Tests', ' Level II Cardiac Imaging',
       ' Level 2 Hospital Clinic Visits',
       ' Level 3 Hospital Clinic Visits',
       ' Level 4 Hospital Clinic Visits',
       ' Level 5 Hospital Clinic Visits',
       ' Level IV Endoscopy Upper Airway',
       ' Level II Extended EEG, Sleep, and Cardiovascular Studies',
       ' Level 1 Hospital Clinic Visits',
       ' Level I Debridement & Destruction', ' Level III Pulmonary Tests',
       ' Level III Echocardiogram Without Contrast',
       ' Level III Nerve Injections',
       ' Level I Electronic Analysis of Devices',
       ' Level I Excision/ Biopsy', ' Level IV Nerve Injections',
       ' Level II Nerve Injections',
       ' Level II Electronic Analysis of Devices',
       ' Level II Eye Tests & Treatments',
       ' Level III Endoscopy Upper Airway'], dtype=object)

In [15]:
# Define a dictionary to map the original levels to their replacements
level_mapping = {
    'Level 1': 'Level I',
    'Level 2': 'Level II',
    'Level 3': 'Level III',
    'Level 4': 'Level IV',
    'Level 5': 'Level V'
}
outpatient_charges['apc_service'] = outpatient_charges['apc_service'].replace(level_mapping, regex=True)

### Load Inpatient Charges Data

In [16]:
# Define a function to load inpatient data
def load_inpatient_data(folder_path):
    
    # Create a list for the years we want to load data for
    years = [2011, 2012, 2013]

    # Initialize an empty list
    inpatient_dataframes = []

    # Iterate through each json file in the folder
    for year in years:

        # Create a variable file_path
        file_path = os.path.join(folder_path, f"inpatient_{year}.json")

        # Read the json file into a dataframe
        df = pd.read_json(file_path)

        # Add year column
        df.insert(0, 'year', year)

        # Append the list with the dataframes
        inpatient_dataframes.append(df)

    return inpatient_dataframes[0], inpatient_dataframes[1], inpatient_dataframes[2]

In [19]:
# Use 'load_inpatient_data' function to read data from directory path
inpatient_2011, inpatient_2012, inpatient_2013 = load_inpatient_data(r"C:\Users\Injelwa\OneDrive\Desktop\Savannah")

In [20]:
# Display summary information for inpatient_2011 data
inpatient_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   year                                  10000 non-null  int64
 1   provider_id                           10000 non-null  int64
 2   provider_name                         10000 non-null  object
 3   provider_street_address               10000 non-null  object
 4   provider_city                         10000 non-null  object
 5   provider_state                        10000 non-null  object
 6   provider_zipcode                      10000 non-null  int64
 7   hospital_referral_region_description  10000 non-null  object
 8   total_discharges                      10000 non-null  int64
 9   average_covered_charges               10000 non-null  float64
 10  average_total_payments                10000 non-null  float64
 11  average_medicare_payments             10000 non-null  float64
 12  icd_category                          10000 non-null  object
dtypes: float64(3), int64(4), object(6)
memory usage: 1015.8+ KB

In [21]:
# Display summary information for inpatient_2012 data
inpatient_2012.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   year                                  10000 non-null  int64
 1   provider_id                           10000 non-null  int64
 2   provider_name                         10000 non-null  object
 3   provider_street_address               10000 non-null  object
 4   provider_city                         10000 non-null  object
 5   provider_state                        10000 non-null  object
 6   provider_zipcode                      10000 non-null  int64
 7   hospital_referral_region_description  10000 non-null  object
 8   total_discharges                      10000 non-null  int64
 9   average_covered_charges               10000 non-null  float64
 10  average_total_payments                10000 non-null  float64
 11  average_medicare_payments             10000 non-null  float64
 12  icd_category                          10000 non-null  object
dtypes: float64(3), int64(4), object(6)
memory usage: 1015.8+ KB

In [22]:
# Display summary information for inpatient_2013 data
inpatient_2013.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   year                                  10000 non-null  int64
 1   provider_id                           10000 non-null  int64
 2   provider_name                         10000 non-null  object
 3   provider_street_address               10000 non-null  object
 4   provider_city                         10000 non-null  object
 5   provider_state                        10000 non-null  object
 6   provider_zipcode                      10000 non-null  int64
 7   hospital_referral_region_description  10000 non-null  object
 8   total_discharges                      10000 non-null  int64
 9   average_covered_charges               10000 non-null  float64
 10  average_total_payments                10000 non-null  float64
 11  average_medicare_payments             10000 non-null  float64
 12  icd_category                          10000 non-null  object
dtypes: float64(3), int64(4), object(6)
memory usage: 1015.8+ KB

In [23]:
# Combine the inpatient charge data for 2011, 2012 and 2013 into a single DataFrame.
inpatient_charges = pd.concat([inpatient_2011, inpatient_2012, inpatient_2013], ignore_index=True)
inpatient_charges.head()

,year,provider_id,provider_name,provider_street_address,provider_city,provider_state,provider_zipcode,hospital_referral_region_description,total_discharges,average_covered_charges,average_total_payments,average_medicare_payments,icd_category
0,2011,450270,LAKE WHITNEY MEDICAL CENTER,200 N SAN JACINTO STREET,WHITNEY,TX,76692,TX - Waco,15,2459.400000,2901.266667,2075.400000,G81
1,2011,450270,LAKE WHITNEY MEDICAL CENTER,200 N SAN JACINTO STREET,WHITNEY,TX,76692,TX - Waco,35,2749.942857,4784.514286,4018.542857,T79
2,2011,450270,LAKE WHITNEY MEDICAL CENTER,200 N SAN JACINTO STREET,WHITNEY,TX,76692,TX - Waco,12,3133.583333,3579.583333,2738.583333,I02
3,2011,450270,LAKE WHITNEY MEDICAL CENTER,200 N SAN JACINTO STREET,WHITNEY,TX,76692,TX - Waco,18,3282.277778,3790.166667,3214.222222,D18
4,2011,370171,W W HASTINGS INDIAN HOSPITAL,100 S BLISS AVENUE,TAHLEQUAH,OK,74464,OK - Tulsa,11,3534.000000,6441.000000,5520.636364,P12

In [24]:
# Load general info data
general_info = pd.read_csv(r"C:\Users\Injelwa\OneDrive\Desktop\Savannah\general_info.csv")
general_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5336 entries, 0 to 5335
Data columns (total 38 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   provider_id                                            5336 non-null   object
 1   hospital_name                                          5336 non-null   object
 2   address                                                5336 non-null   object
 3   city                                                   5336 non-null   object
 4   state                                                  5336 non-null   object
 5   zip_code                                               5336 non-null   int64
 6   county_name                                            5336 non-null   object
 7   phone_number                                           5336 non-null   object
 8   hospital_type                                          5336 non-null   object
 9   hospital_ownership                                     5336 non-null   object
 10  emergency_services                                     5336 non-null   bool
 11  meets_criteria_for_promoting_interoperability_of_ehrs  3886 non-null   object
 12  hospital_overall_rating                                5336 non-null   object
 13  hospital_overall_rating_footnote                       2066 non-null   float64
 14  mortality_group_measure_count                          5336 non-null   object
 15  facility_mortaility_measures_count                     5336 non-null   object
 16  mortality_measures_better_count                        5336 non-null   object
 17  mortality_measures_no_different_count                  5336 non-null   object
 18  mortality_measures_worse_count                         5336 non-null   object
 19  mortaility_group_footnote                              1373 non-null   float64
 20  safety_measures_count                                  5336 non-null   object
 21  facility_care_safety_measures_count                    5336 non-null   object
 22  safety_measures_better_count                           5336 non-null   object
 23  safety_measures_no_different_count                     5336 non-null   object
 24  safety_measures_worse_count                            5336 non-null   object
 25  safety_group_footnote                                  1781 non-null   float64
 26  readmission_measures_count                             5336 non-null   object
 27  facility_readmission_measures_count                    5336 non-null   object
 28  readmission_measures_better_count                      5336 non-null   object
 29  readmission_measures_no_different_count                5336 non-null   object
 30  readmission_measures_worse_count                       5336 non-null   object
 31  readmission_measures_footnote                          983 non-null    float64
 32  patient_experience_measures_count                      5336 non-null   object
 33  facility_patient_experience_measures_count             5336 non-null   object
 34  patient_experience_measures_footnote                   2045 non-null   float64
 35  timely_and_effective_care_measures_count               5336 non-null   object
 36  facility_timely_and_effective_care_measures_count      5336 non-null   object
 37  timely_and_effective_care_measures_footnote            929 non-null    float64
dtypes: bool(1), float64(6), int64(1), object(30)
memory usage: 1.5+ MB

In [33]:
# Filter out rows containing 'F' in 'provider id'
general_info = general_info[~general_info['provider_id'].str.contains('F')]

In [34]:
# Count the number of NaN values in each column
general_info.isnull().sum()

provider_id                                                 0
hospital_name                                               0
address                                                     0
city                                                        0
state                                                       0
zip_code                                                    0
county_name                                                 0
phone_number                                                0
hospital_type                                               0
hospital_ownership                                          0
emergency_services                                          0
meets_criteria_for_promoting_interoperability_of_ehrs    1415
hospital_overall_rating                                     0
hospital_overall_rating_footnote                         3270
mortality_group_measure_count                               0
facility_mortaility_measures_count                          0
mortality_measures_better_count                             0
mortality_measures_no_different_count                       0
mortality_measures_worse_count                              0
mortaility_group_footnote                                3963
safety_measures_count                                       0
facility_care_safety_measures_count                         0
safety_measures_better_count                                0
safety_measures_no_different_count                          0
safety_measures_worse_count                                 0
safety_group_footnote                                    3555
readmission_measures_count                                  0
facility_readmission_measures_count                         0
readmission_measures_better_count                           0
readmission_measures_no_different_count                     0
readmission_measures_worse_count                            0
readmission_measures_footnote                            4353
patient_experience_measures_count                           0
facility_patient_experience_measures_count                  0
patient_experience_measures_footnote                     3291
timely_and_effective_care_measures_count                    0
facility_timely_and_effective_care_measures_count           0
timely_and_effective_care_measures_footnote              4407
dtype: int64

In [35]:
# Fill NaN values in 'meets_criteria_for_promoting_interoperability_of_ehrs' with 'False'
general_info['meets_criteria_for_promoting_interoperability_of_ehrs'].fillna('False', inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_860\2928257377.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  general_info['meets_criteria_for_promoting_interoperability_of_ehrs'].fillna('False', inplace=True)

In [36]:
# Fill all NaN values in the DataFrame with 'Not Available'
general_info.fillna('Not Available', inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_860\1657790317.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not Available' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  general_info.fillna('Not Available', inplace=True)

In [37]:
general_info.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5301 entries, 0 to 5335
Data columns (total 38 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   provider_id                                            5301 non-null   object
 1   hospital_name                                          5301 non-null   object
 2   address                                                5301 non-null   object
 3   city                                                   5301 non-null   object
 4   state                                                  5301 non-null   object
 5   zip_code                                               5301 non-null   int64
 6   county_name                                            5301 non-null   object
 7   phone_number                                           5301 non-null   object
 8   hospital_type                                          5301 non-null   object
 9   hospital_ownership                                     5301 non-null   object
 10  emergency_services                                     5301 non-null   bool
 11  meets_criteria_for_promoting_interoperability_of_ehrs  5301 non-null   object
 12  hospital_overall_rating                                5301 non-null   object
 13  hospital_overall_rating_footnote                       5301 non-null   object
 14  mortality_group_measure_count                          5301 non-null   object
 15  facility_mortaility_measures_count                     5301 non-null   object
 16  mortality_measures_better_count                        5301 non-null   object
 17  mortality_measures_no_different_count                  5301 non-null   object
 18  mortality_measures_worse_count                         5301 non-null   object
 19  mortaility_group_footnote                              5301 non-null   object
 20  safety_measures_count                                  5301 non-null   object
 21  facility_care_safety_measures_count                    5301 non-null   object
 22  safety_measures_better_count                           5301 non-null   object
 23  safety_measures_no_different_count                     5301 non-null   object
 24  safety_measures_worse_count                            5301 non-null   object
 25  safety_group_footnote                                  5301 non-null   object
 26  readmission_measures_count                             5301 non-null   object
 27  facility_readmission_measures_count                    5301 non-null   object
 28  readmission_measures_better_count                      5301 non-null   object
 29  readmission_measures_no_different_count                5301 non-null   object
 30  readmission_measures_worse_count                       5301 non-null   object
 31  readmission_measures_footnote                          5301 non-null   object
 32  patient_experience_measures_count                      5301 non-null   object
 33  facility_patient_experience_measures_count             5301 non-null   object
 34  patient_experience_measures_footnote                   5301 non-null   object
 35  timely_and_effective_care_measures_count               5301 non-null   object
 36  facility_timely_and_effective_care_measures_count      5301 non-null   object
 37  timely_and_effective_care_measures_footnote            5301 non-null   object
dtypes: bool(1), int64(1), object(36)
memory usage: 1.5+ MB

In [38]:
# Export the dataframes to an excel workbook
with pd.ExcelWriter('healthcare_dataset.xlsx') as writer:
    outpatient_charges.to_excel(writer, sheet_name='outpatient_charges', index=False)
    inpatient_charges.to_excel(writer, sheet_name='inpatient_charges', index=False)
    general_info.to_excel(writer, sheet_name='hospital_gen_info', index=False)